# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x 
      - name: npm install command
        run: cd dist && npm install
      - name: Run build command
        run: cd dist && npm run build
      - name: Deploy
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.2.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }} # see the Configuration section for how you can create secrets
          #build_configuration: staging # The build environment for the app. please look configurations in your angular.json
          base_href: https://liangtianwang.github.io/retail-engine/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
          #deploy_branch: gh-pages # The branch the action should deploy to.
          build_folder: dist/re # The folder where your project is supposed to be after running ng build by the action.
